In [1]:
from array import array
import itertools
import time
import math

import sys
#####For NERSC:####
#sys.path.insert(0,'/usr/common/software/rootpy/')
import root_numpy
import numpy as np

import matplotlib
import matplotlib.pyplot as plt

#import astroML.plotting as aml
#import iminuit
import pandas as pd
import root_pandas as rpd
from root_pandas import read_root
import ROOT
from ROOT import TH1D
from ROOT import SetOwnership
from matplotlib.ticker import NullFormatter
from ROOT import TLatex
%matplotlib inline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

Welcome to ROOTaaS 6.06/06


In [3]:
print("                           Proton-Proton")
NN_pp_FF = np.load("npy_files/NN_pp_Fragmentation_Functions.npy")
NN_pp_FF_Errors = np.load("npy_files/NN_pp_Fragmentation_Function_Errors.npy")
print("Neural Net")
print(NN_pp_FF_Errors/NN_pp_FF)

L0_pp_FF = np.load("npy_files/LO_pp_Fragmentation_Functions.npy")
L0_pp_FF_Errors = np.load("npy_files/LO_pp_Fragmentation_Function_Errors.npy")
print("Lambda0")
print(L0_pp_FF_Errors/L0_pp_FF)

print("")


print("                           Proton-Lead")
NN_pPb_FF = np.load("npy_files/NN_pPb_Fragmentation_Functions.npy")
NN_pPb_FF_Errors = np.load("npy_files/NN_pPb_Fragmentation_Function_Errors.npy")
print("Neural Net")
print(NN_pPb_FF_Errors/NN_pPb_FF)

L0_pPb_FF = np.load("npy_files/LO_pPb_Fragmentation_Functions.npy")
L0_pPb_FF_Errors = np.load("npy_files/LO_pPb_Fragmentation_Function_Errors.npy")
print("Lambda0")
print(L0_pPb_FF_Errors/L0_pPb_FF)

#Load purity FF uncertainties:
L0_pp_FF_purity_Uncertainty = np.load("npy_files/LO_pp_FF_purity_Uncertainty.npy")
L0_pPb_FF_purity_Uncertainty = np.load("npy_files/LO_pPb_FF_purity_Uncertainty.npy")
NN_pp_FF_purity_Uncertainty = np.load("npy_files/LO_pp_FF_purity_Uncertainty.npy")
NN_pPb_FF_purity_Uncertainty = np.load("npy_files/LO_pPb_FF_purity_Uncertainty.npy")


                           Proton-Proton
Neural Net
[[ 0.27299453  0.2013812   0.27463495  0.3077216   0.26809647  0.72738058]
 [ 0.8232182   0.32602943  0.34031771  0.30016656  0.2975693   1.21460661]
 [ 0.1637013   0.18506315  0.13834762  0.16891863  0.29199634  0.47811077]
 [ 0.19653105  0.15808036  0.2750548   0.28117445  0.3694252   0.80587106]]
Lambda0
[[ 0.27563823  0.18192028  0.20736659  0.30404485  0.19926382  0.41536878]
 [ 0.84617789  0.22450306  0.23945741  0.27022019  0.19878411  0.47048644]
 [ 0.13294145  0.12538455  0.11327941  0.14327788  0.2230017   0.25936931]
 [ 0.16071569  0.12540151  0.14863659  0.2031258   0.31640144  0.68320949]]

                           Proton-Lead
Neural Net
[[ 0.11503185  0.10769425  0.15340464  0.21113623  0.21604927  0.67397466]
 [ 0.16952166  0.22821763  0.16383633  0.18064085  0.17455689  0.46746818]
 [ 0.13457647  0.10590242  0.16061866  0.12306398  0.21961831  0.25626646]
 [ 0.11933318  0.19282444  0.25021627  0.20740125  0.31324052 